### PR TITLE
Mention submodules and early state of development

### PR DESCRIPTION
**Pull request by razzeee**

### CODE REVIEW

**Review by matheus23 — APPROVED** [review]

**Comment by matheus23** [comment]
I'll merge this right now, but eventually I want to replace many parts of the README. There's quite some stuff that needs some addressing.

I use a lot more libraries. It would make sense to add a comment in the 'spirit' of the 'Libraries used' Section instead of listing them actually. Something like 'combines haskell-lsp with the elm compiler as a library to check elm code'. 

Also the 'Conceptual inner workings' Section is factually correct right now, but I want to move away from creating many language servers, each per `elm.json` file, since the LSP could and should be aware of multiple `elm.json` files and handle those situations.

**Comment by razzeee** [comment]
Sounds sane to me.

I also wanted to add a `Features` section which I forgot about.
Should highlight that we only have diagnostics right now.

**Comment by matheus23** [comment]
Do you want to add this to this PR? I think that would make sense.

**Comment by razzeee** [comment]
Pushed another change, should I squash this down to one commit?

**Review by matheus23 — APPROVED** [review]

**Pull request merged**
